# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 051949e4907016a840bd69398ae98b5ad5cd524925d8a8277d6fdeeb29913e2e87a06b2da3c7ad7482b13b99ff3abffc69cc1866da41c7b4d431592aed01ece9

test:
  secret_key_base: e08c62e8a4dbfc0f9f92746b8694e09b356e606e3027d9d0ba29a9646fa12ea2562bfe4cf72e07a79dcb296ba574f59860432cfd01fb18da241dfefdbd4ff499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
